services:
  postgres-db:
    image: postgres:17.5
    container_name: sci-center-postgres-db
    environment:
      POSTGRES_USER: sci_center
      POSTGRES_PASSWORD: sci_center
      POSTGRES_DB: sci_center
    ports:
      - "5434:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d