services:
  postgres-db:
    image: postgres:latest
    container_name: sci-center-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d