INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('AHL', 'Arheologija', 'A');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('IST', 'Istorija', 'A');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('PSH', 'Psihologija', 'A');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('LIN', 'Lingvistika', 'A');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('DRH', 'Seminar drustveno-humanistickih nauka', 'A');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('HEM', 'Hemija', 'B');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('BIO', 'Biologija', 'B');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('GEO', 'Geografija', 'B');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('GGR', 'Geografija', 'B');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('BMD', 'Biomedicina', 'B');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('EBH', 'Eksperimentalna biologija i hemija', 'B');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('AST', 'Astronomija', 'C');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('FIZ', 'Fizika', 'C');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('MAT', 'Matematika', 'C');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('RAC', 'Racunarstvo', 'C');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('ELE', 'Elektronika', 'C');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('TEH', 'Seminar tehnickih nauka', 'C');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('DIZ', 'Dizajn', 'D');
INSERT INTO naucni_program (id_prog, naz, id_od) VALUES ('ALL', 'Seminar kombinovanih nauka', 'E');
