INSERT INTO rukovodi (osoba_id, id_prog, upr) VALUES (1, 'RAC', TRUE);
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (2, 'RAC');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (3, 'AHL');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (4, 'AST');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (5, 'AST');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (6, 'BIO');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (7, 'BIO');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (8, 'BMD');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (9, 'BMD');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (10, 'DIZ');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (11, 'DIZ');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (12, 'DRH');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (13, 'DRH');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (14, 'EBH');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (15, 'EBH');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (16, 'ELE');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (18, 'GGR');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (19, 'GGR');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (20, 'GEO');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (21, 'GEO');
INSERT INTO rukovodi (osoba_id, id_prog, upr) VALUES (22, 'HEM', TRUE);
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (23, 'HEM');
INSERT INTO rukovodi (osoba_id, id_prog, upr) VALUES (24, 'IST', TRUE);
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (25, 'ALL');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (26, 'LIN');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (27, 'LIN');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (28, 'MAT');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (29, 'MAT');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (30, 'PSH');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (31, 'TEH');
INSERT INTO rukovodi (osoba_id, id_prog) VALUES (32, 'TEH');
